<!DOCTYPE html>
<html lang="en"> 
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="src-css/skeleton.css">

        
        
    </head>
    <body>
        <div class="container">
            <div class="columns">
                <div class="one-third column"></div>
                <div class="one-third column">
                    <h3>You didnt enter any string</h3>



                    <a href="./simulacram.html" class="button button-primary">Try again</a>



                </div>
                <div class="one-third column"></div>
            </div>
        </div>
    </body> 
</html>




